### PR TITLE
Upgrade from `peter-evans/create-issue-from-file@v2` to `v4`

### LINKED ISSUE #21: `ds-gitflows-template` set-up fails
## Diagnosis

GitHub actions fails after cloning the template and having @lindsayplatt kick off the initial build by starring the cloned repo. Here are a few screenshots and a [link to a failing build](https://github.com/USGS-R/ds-gitflows-mjcashman-usgs/runs/7958294578?check_suite_focus=true#step:5:132):

image

image

We also know that this repo worked as recently as 8/4 because Jesse successfully ran the gitflows training for two new hires. 

We found a few red herrings:
* https://github.com/conan-io/conan/issues/7092#issuecomment-634065852
* https://github.com/actions/setup-python/issues/398

I am noting them here because the _lack_ of any calls to `python -m pip install` helped me find the culprit. This led me to dig into [Peter Evans' `create-issue-from-file` repo](https://github.com/peter-evans/create-issue-from-file) because it _is_ called multiple times from [.github/workflows/setup.yml](https://github.com/USGS-R/ds-gitflows-template/blob/49cc57617d5ae2e3d22c859fbaaf381cf4e62265/.github/workflows/setup.yml#L44). He had [two PRs merged 4 days ago](https://github.com/peter-evans/create-issue-from-file/pulls?q=is%3Apr+is%3Aclosed), upgrading to [v4](https://github.com/peter-evans/create-issue-from-file/releases/tag/v4.0.0).

## Troubleshooting a solution
To troubleshoot this I cloned this repo, [made my own template](https://github.com/padilla410/ds-gitflows-tempate), and assigned myself as the [`github.actor`](https://github.com/padilla410/ds-gitflows-tempate/blob/f9fa1d0eabe1a708d6804f5a0c39ad7b34f30e0c/.github/workflows/setup.yml#L19), updated [`Issue 1`](https://github.com/padilla410/ds-gitflows-tempate/blob/f9fa1d0eabe1a708d6804f5a0c39ad7b34f30e0c/.github/workflows/setup.yml#L44), and then tried to kick-off a new repo. With the stated updates, this repo successfully [builds `Issue 1` and fails on `Issue 2`](https://github.com/padilla410/ds-gitflows-v3/runs/7959187034?check_suite_focus=true) which was the expected action.

I also verified that changing all references to from v2 to v4 will allow the build to [successfully complete](https://github.com/padilla410/ds-gitflows-v4/runs/7959680623?check_suite_focus=true).

I am now going to submit a PR to this repo that updates all actions from `peter-evans/create-issue-from-file@v2` to `peter-evans/create-issue-from-file@v4`

### PR DESCRIPTION
**Pull request by padilla410**
## Overview

This PR does two things:
1. Resolves the the bug described in detail in #21 
2. Changes the `github.actor` from @lindsayplatt  to @padilla410

Issue #21 was discovered when I tried to develop repos for the National IWAAs GitFlows training that I am going to run later this week. The problem and verification of the bug fix are fully described in the issue.

Lindsay and I also decided to switch the `github.actor` from her handle to mine because she will have limited availability to help troubleshoot future problems and kick-off new builds.

Closes #21 

## PR Review Request
Lindsay, what is the best way to test this? Ideally, I would like you to checkout my template fork and create a repo so that I can kickoff a build.

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@padilla410 see if you can star this and have the build work: https://github.com/lindsayplatt/test-jpadilla-ghactions-updates

**Comment by padilla410** [comment]
@lindsayplatt this repo (https://github.com/lindsayplatt/test-jpadilla-ghactions-updates) won't work because [you are the owner](https://github.com/lindsayplatt/test-jpadilla-ghactions-updates/blob/e1fa123dae645d051e8649370495aeef030bc5b6/.github/workflows/setup.yml#L19) and the [version fixes are not there](https://github.com/lindsayplatt/test-jpadilla-ghactions-updates/blob/e1fa123dae645d051e8649370495aeef030bc5b6/.github/workflows/setup.yml#L44).

**Comment by lindsayplatt** [comment]
@padilla410 I think we need to make sure that this is checked! I am going to delete my first attempt and try again. I think me making it and you starring the repo is the test we want, though. It shouldn't matter who the owner is. In fact, we want you to be able to star repos that others might make and have it work.

image

I think I may also switch the default branch on my test repo. When you "star" a repo, I don't think you are starring a specific branch and I am concerned it will still try to use the `main` and not your fixes in `upgrade-pe-v4`.

**Comment by lindsayplatt** [comment]
@padilla410 let's see if this will work! https://github.com/lindsayplatt/test-jpadilla-ghactions-updates

**Comment by padilla410** [comment]
Yes! Verified: https://github.com/lindsayplatt/test-jpadilla-ghactions-updates/runs/7975459852?check_suite_focus=true

image

**Comment by lindsayplatt** [comment]
I am going to delete that repo now, so the links won't work but we do have a record of how we did this in the comments and screenshots here :)

**Pull request merged**
